# Generated by Django 4.0.5 on 2022-07-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0011_remove_familyinformation_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('fathers_number', models.CharField(max_length=50)),
                ('mothers_number', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_relation', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'FamilyInformation',
                'verbose_name_plural': 'FamilyInformations',
            },
        ),
    ]
