# Generated by Django 4.0.5 on 2022-07-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0011_remove_familyinformation_student_and_more'),
        ('batch', '0003_alter_faculty_options_alter_semester_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_registration_number', models.CharField(max_length=100)),
                ('symbol_number', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='batch.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='batch.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='batch.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'CollegeInformation',
                'verbose_name_plural': 'CollegeInformations',
                'ordering': ('symbol_number',),
            },
        ),
    ]
