# Generated by Django 4.0.5 on 2022-07-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_faculty_semester_alter_batch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty_name', 'verbose_name_plural': 'Faculty_names'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Semester_name', 'verbose_name_plural': 'Semester_names'},
        ),
    ]
