# Generated by Django 4.0.5 on 2022-07-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('citizenship', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('temp_address', models.CharField(blank=True, max_length=150, null=True)),
                ('perm_address', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_alumi', models.BooleanField(default=False)),
                ('picture', models.ImageField(upload_to='student_picture')),
            ],
        ),
    ]
