# Generated by Django 4.0.5 on 2022-07-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='scooter.png', upload_to='student_picture'),
        ),
    ]
