# Generated by Django 4.0.5 on 2022-07-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='scooter.png', null=True, upload_to='student_picture'),
        ),
    ]
