# Generated by Django 4.0.5 on 2022-07-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_alumi',
            field=models.BooleanField(),
        ),
    ]
