# Generated by Django 4.0.5 on 2022-07-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_is_active_alter_student_is_alumi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_alumi',
        ),
        migrations.RemoveField(
            model_name='student',
            name='picture',
        ),
    ]
