# Generated by Django 4.0.5 on 2022-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_student_is_active_remove_student_is_alumi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_alumi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, default='scooter.png', null=True, upload_to='student_picture'),
        ),
    ]
