# Generated by Django 4.0.5 on 2022-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_is_active_student_is_alumi_student_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name',), 'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
        migrations.AlterField(
            model_name='student',
            name='citizenship',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
