# Generated by Django 4.0.5 on 2022-07-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_alter_faculty_options_alter_semester_options'),
        ('student', '0008_alter_student_options_alter_student_citizenship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('fathers_number', models.CharField(max_length=50)),
                ('mothers_number', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_relation', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'EducationInformation',
                'verbose_name_plural': 'EducationInformations',
            },
        ),
        migrations.CreateModel(
            name='EducationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_number', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=50)),
                ('cgpa', models.CharField(max_length=50)),
                ('passed_year', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'EducationInformation',
                'verbose_name_plural': 'EducationInformations',
                'ordering': ('symbol_number',),
            },
        ),
        migrations.CreateModel(
            name='CollegeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_registration_number', models.CharField(max_length=100)),
                ('symbol_number', models.CharField(max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='batch.batch')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='batch.faculty')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='batch.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'EducationInformation',
                'verbose_name_plural': 'EducationInformations',
                'ordering': ('symbol_number',),
            },
        ),
    ]
