# Generated by Django 4.0.5 on 2022-07-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_collegeinformation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyinformation',
            name='student',
        ),
        migrations.DeleteModel(
            name='CollegeInformation',
        ),
        migrations.DeleteModel(
            name='FamilyInformation',
        ),
    ]
